/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UIManager;

import java.awt.Dimension;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Suchanan
 */
public class GamePlayDisplayGUI extends javax.swing.JFrame {

    public Object getDeckCardPanel;

    public GamePlayDisplayGUI() {
        initComponents();
        
//        Dimension hitButtonSize = new Dimension(150, 30);
//        hitButton.setMaximumSize(hitButtonSize);
//        hitButton.setMinimumSize(hitButtonSize);
//        hitButton.setPreferredSize(hitButtonSize);
//        
//        Dimension buttonPanelSize = new Dimension(150, 200);
//        buttonPanel.setMaximumSize(buttonPanelSize);
//        buttonPanel.setMinimumSize(buttonPanelSize);
//        buttonPanel.setPreferredSize(buttonPanelSize);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonPanel = new javax.swing.JPanel();
        hitButton = new javax.swing.JButton();
        standButton = new javax.swing.JButton();
        scoreLabel = new javax.swing.JLabel();
        playerOneTable = new javax.swing.JPanel();
        playerTwoTable = new javax.swing.JPanel();
        trumpChipPlayerTwoPanel = new javax.swing.JPanel();
        playerOneNamePanel = new javax.swing.JPanel();
        trumpHoldChipPlayerOnePanel = new javax.swing.JPanel();
        trumpChipPlayerOnePanel = new javax.swing.JPanel();
        deckCardPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        playerTwoNamePanel = new javax.swing.JPanel();
        scoreGamePlayerOnePanel = new javax.swing.JPanel();
        scoreGamePlayerOneLabel = new javax.swing.JLabel();
        scoreGamePlayerTwoPanel = new javax.swing.JPanel();
        scoreGamePlayerTwoLabel = new javax.swing.JLabel();
        trumpHoldChipPlayerTwoPanel = new javax.swing.JPanel();
        vsPanel = new javax.swing.JPanel();
        vsLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setBackground(new java.awt.Color(204, 255, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonPanel.setPreferredSize(new java.awt.Dimension(150, 200));

        hitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/HitButton_1.PNG"))); // NOI18N

        standButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/StandButton_1.PNG"))); // NOI18N

        scoreLabel.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        scoreLabel.setText("Score : ");
        scoreLabel.setPreferredSize(new java.awt.Dimension(150, 100));

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buttonPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buttonPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(standButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(standButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.add(buttonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1118, 520, 156, 212));

        playerOneTable.setBackground(new java.awt.Color(102, 0, 0));
        playerOneTable.setBorder(javax.swing.BorderFactory.createMatteBorder(30, 30, 30, 30, new javax.swing.ImageIcon("C:\\Users\\Suchanan\\OneDrive\\Documents\\NetBeansProjects\\Untitled-BlackJack\\src\\resources\\Table.PNG"))); // NOI18N
        jPanel1.add(playerOneTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 520, 730, 240));

        playerTwoTable.setBackground(new java.awt.Color(102, 0, 0));
        playerTwoTable.setBorder(javax.swing.BorderFactory.createMatteBorder(30, 30, 30, 30, new javax.swing.ImageIcon("C:\\Users\\Suchanan\\OneDrive\\Documents\\NetBeansProjects\\Untitled-BlackJack\\src\\resources\\Table.PNG"))); // NOI18N
        playerTwoTable.setPreferredSize(new java.awt.Dimension(720, 330));
        jPanel1.add(playerTwoTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 730, 240));
        jPanel1.add(trumpChipPlayerTwoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 600, 70));
        jPanel1.add(playerOneNamePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 640, 250, 90));

        javax.swing.GroupLayout trumpHoldChipPlayerOnePanelLayout = new javax.swing.GroupLayout(trumpHoldChipPlayerOnePanel);
        trumpHoldChipPlayerOnePanel.setLayout(trumpHoldChipPlayerOnePanelLayout);
        trumpHoldChipPlayerOnePanelLayout.setHorizontalGroup(
            trumpHoldChipPlayerOnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        trumpHoldChipPlayerOnePanelLayout.setVerticalGroup(
            trumpHoldChipPlayerOnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        jPanel1.add(trumpHoldChipPlayerOnePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 250, 160));

        trumpChipPlayerOnePanel.setAutoscrolls(true);
        trumpChipPlayerOnePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(trumpChipPlayerOnePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 600, 70));

        deckCardPanel.setBackground(new java.awt.Color(255, 102, 255));
        deckCardPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Suchanan\\OneDrive\\Documents\\NetBeansProjects\\Untitled-BlackJack\\resources\\download.png")); // NOI18N
        jLabel2.setText("jLabel2");
        deckCardPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 210));

        jPanel1.add(deckCardPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 270, 150, 210));

        playerTwoNamePanel.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.add(playerTwoNamePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 250, 90));

        scoreGamePlayerOneLabel.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        scoreGamePlayerOneLabel.setText("0");

        javax.swing.GroupLayout scoreGamePlayerOnePanelLayout = new javax.swing.GroupLayout(scoreGamePlayerOnePanel);
        scoreGamePlayerOnePanel.setLayout(scoreGamePlayerOnePanelLayout);
        scoreGamePlayerOnePanelLayout.setHorizontalGroup(
            scoreGamePlayerOnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, scoreGamePlayerOnePanelLayout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(scoreGamePlayerOneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        scoreGamePlayerOnePanelLayout.setVerticalGroup(
            scoreGamePlayerOnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scoreGamePlayerOneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        jPanel1.add(scoreGamePlayerOnePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, 180, 80));

        scoreGamePlayerTwoLabel.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        scoreGamePlayerTwoLabel.setText("0");

        javax.swing.GroupLayout scoreGamePlayerTwoPanelLayout = new javax.swing.GroupLayout(scoreGamePlayerTwoPanel);
        scoreGamePlayerTwoPanel.setLayout(scoreGamePlayerTwoPanelLayout);
        scoreGamePlayerTwoPanelLayout.setHorizontalGroup(
            scoreGamePlayerTwoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, scoreGamePlayerTwoPanelLayout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addComponent(scoreGamePlayerTwoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        scoreGamePlayerTwoPanelLayout.setVerticalGroup(
            scoreGamePlayerTwoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scoreGamePlayerTwoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(scoreGamePlayerTwoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 340, 180, 80));

        trumpHoldChipPlayerTwoPanel.setBackground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout trumpHoldChipPlayerTwoPanelLayout = new javax.swing.GroupLayout(trumpHoldChipPlayerTwoPanel);
        trumpHoldChipPlayerTwoPanel.setLayout(trumpHoldChipPlayerTwoPanelLayout);
        trumpHoldChipPlayerTwoPanelLayout.setHorizontalGroup(
            trumpHoldChipPlayerTwoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        trumpHoldChipPlayerTwoPanelLayout.setVerticalGroup(
            trumpHoldChipPlayerTwoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        jPanel1.add(trumpHoldChipPlayerTwoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 250, 160));

        vsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vsLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        vsLabel.setText("VS");
        vsPanel.add(vsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 60));

        jPanel1.add(vsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 350, 70, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Suchanan\\OneDrive\\Documents\\NetBeansProjects\\Untitled-BlackJack\\src\\resources\\GamePlayBackground.PNG")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 1290, 800));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    public void init() {
        initComponents();
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setVisible(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel deckCardPanel;
    private javax.swing.JButton hitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel playerOneNamePanel;
    private javax.swing.JPanel playerOneTable;
    private javax.swing.JPanel playerTwoNamePanel;
    private javax.swing.JPanel playerTwoTable;
    private javax.swing.JLabel scoreGamePlayerOneLabel;
    private javax.swing.JPanel scoreGamePlayerOnePanel;
    private javax.swing.JLabel scoreGamePlayerTwoLabel;
    private javax.swing.JPanel scoreGamePlayerTwoPanel;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JButton standButton;
    private javax.swing.JPanel trumpChipPlayerOnePanel;
    private javax.swing.JPanel trumpChipPlayerTwoPanel;
    private javax.swing.JPanel trumpHoldChipPlayerOnePanel;
    private javax.swing.JPanel trumpHoldChipPlayerTwoPanel;
    private javax.swing.JLabel vsLabel;
    private javax.swing.JPanel vsPanel;
    // End of variables declaration//GEN-END:variables

    public JPanel getButtonPanel() {
        return buttonPanel;
    }

    public void setButtonPanel(JPanel buttonPanel) {
        this.buttonPanel = buttonPanel;
    }

    public JButton getHitButton() {
        return hitButton;
    }

    public void setHitButton(JButton hitButton) {
        this.hitButton = hitButton;
    }

    public JLabel getjLabel1() {
        return scoreGamePlayerTwoLabel;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.scoreGamePlayerTwoLabel = jLabel1;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getPlayerOneTable() {
        return playerOneTable;
    }

    public void setPlayerOneTable(JPanel playerOneTable) {
        this.playerOneTable = playerOneTable;
    }

    public JPanel getPlayerTwoTable() {
        return playerTwoTable;
    }

    public void setPlayerTwoTable(JPanel playerTwoTable) {
        this.playerTwoTable = playerTwoTable;
    }

    public JLabel getScoreLabel() {
        return scoreLabel;
    }

    public void setScoreLabel(JLabel scoreLabel) {
        this.scoreLabel = scoreLabel;
    }

    public JButton getStandButton() {
        return standButton;
    }

    public void setStandButton(JButton standButton) {
        this.standButton = standButton;
    }

    public JPanel getDeckCardPanel() {
        return deckCardPanel;
    }

    public void setDeckCardPanel(JPanel deckCardPanel) {
        this.deckCardPanel = deckCardPanel;
    }

    public JPanel getPlayerOneNamePanel() {
        return playerOneNamePanel;
    }

    public void setPlayerOneNamePanel(JPanel playerOneNamePanel) {
        this.playerOneNamePanel = playerOneNamePanel;
    }

    public JPanel getPlayerTwoNamePanel() {
        return playerTwoNamePanel;
    }

    public void setPlayerTwoNamePanel(JPanel playerTwoNamePanel) {
        this.playerTwoNamePanel = playerTwoNamePanel;
    }

    public JPanel getTrumpChipPlayerOnePanel() {
        return trumpChipPlayerOnePanel;
    }

    public void setTrumpChipPlayerOnePanel(JPanel trumpChipPlayerOnePanel) {
        this.trumpChipPlayerOnePanel = trumpChipPlayerOnePanel;
    }

    public JPanel getTrumpChipPlayerTwoPanel() {
        return trumpChipPlayerTwoPanel;
    }

    public void setTrumpChipPlayerTwoPanel(JPanel trumpChipPlayerTwoPanel) {
        this.trumpChipPlayerTwoPanel = trumpChipPlayerTwoPanel;
    }

    public JPanel getTrumpHoldChipPlayerOnePanel() {
        return trumpHoldChipPlayerOnePanel;
    }

    public void setTrumpHoldChipPlayerOnePanel(JPanel trumpHoldChipPlayerOnePanel) {
        this.trumpHoldChipPlayerOnePanel = trumpHoldChipPlayerOnePanel;
    }

    public JPanel getTrumpHoldChipPlayerTwoPanel() {
        return trumpHoldChipPlayerTwoPanel;
    }

    public void setTrumpHoldChipPlayerTwoPanel(JPanel trumpHoldChipPlayerTwoPanel) {
        this.trumpHoldChipPlayerTwoPanel = trumpHoldChipPlayerTwoPanel;
    }
    
}
